{% set name = "tornado_m2crypto" %}
{% set version = "0.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tornado_m2crypto-{{ version }}.tar.gz
  sha256: f60b1fa913df69a5d520b1e0328de44d44631e01b9cf7d303b1127dc7f8a8e1b

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools_scm
  run:
    - m2crypto
    - python >=3.9
    - tornado ==5.1.1+dirac.*

test:
  imports:
    - tornado_m2crypto
    - tornado_m2crypto.m2httputil
    - tornado_m2crypto.m2iostream
    - tornado_m2crypto.m2netutil
    - tornado_m2crypto.test
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/DIRACGrid/tornado_m2crypto
  summary: Extension for running tornado with M2Crypto instead of the standard python SSL module
  dev_url: https://github.com/DIRACGrid/tornado_m2crypto/
  license: GPL-3.0-or-later
  license_file: LICENSE
