# This workflow creates docker images that are then used for:
#
# - DIRAC distribution (create DIRAC release tarballs)
# - running DIRAC integration tests in GitHub actions
# 
# All created images are then uploaded to GitHub packages

name: Create images

on: push
# on: 
#   schedule:
#     # every Sunday
#     - cron:  '0 0 * * 0'

jobs:
  # Image for running dirac-distribution
  dirac-distribution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          echo $PWD
          ls -l
          docker build -t docker.pkg.github.com/diracgrid/management/dirac-distribution:latest dirac-distribution
      - name: login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username ${{ github.actor }} --password-stdin
      - name: docker push
        run: docker push docker.pkg.github.com/diracgrid/management/dirac-distribution:latest

  # Now the images for running integration tests
  docker-compose-dirac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: docker build -t docker.pkg.github.com/diracgrid/management/docker-compose-dirac:latest docker-compose-dirac
      - name: login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username ${{ github.actor }} --password-stdin
      - name: docker push
        run: docker push docker.pkg.github.com/diracgrid/management/docker-compose-dirac:latest

  cc7-dirac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: docker build -t docker.pkg.github.com/diracgrid/management/cc7-dirac:latest cc7-dirac
      - name: login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username ${{ github.actor }} --password-stdin
      - name: docker push
        run: docker push docker.pkg.github.com/diracgrid/management/cc7-dirac:latest

  slc6-dirac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: docker build -t docker.pkg.github.com/diracgrid/management/slc6-dirac:latest slc6-dirac
      - name: login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username ${{ github.actor }} --password-stdin
      - name: docker push
        run: docker push docker.pkg.github.com/diracgrid/management/slc6-dirac:latest
